In [10]:
#First I need to know that Numpy we use tho handle mastrix (1D,2D)
#Is packge python that provide methods and functions to handle array and matrix
#Is is used in data analysis
#Lets pratice

#first we need to import 
import numpy as np
# after this we can create array with one-dimetions ou two
a=np.array([1,2,3]);
print(a)
# and to create with to tho-dimenseional is that
b=np.array([[1,23,12],[45,12,13]])
#Alright we can use this :
#type(a) to see the type , 
print('Type a :',type(a))
#shape to see the number of element
print('Shape b :',b.shape)
#ndim to see how much dimesional
print('Dim b',b.ndim);
#As you see in b we have two dimensional so for see the specific value in b we use index
print('b[0,1]:',b[0,1])
#but we  can also use this to ond  dimensional
#anyway we also use this b[-1] to retrieved the last number 
# we can use this b[1,:] just to retrieved the among numbers in the the index 1 
#we also use this b[0:1] to change the number in this specif index


[1 2 3]
Type a : <class 'numpy.ndarray'>
Shape b : (2, 3)
Dim b 2
b[0,1]: 23


In [21]:
#Varios methods in Numpy
#What is diference between function and method
#In numpy we have functions as sum()
a=np.array([12,14,16]);
np.sum(a)
a.sum()
#let is talk about dtype
print(a.dtype)
#basycally all the data is define as int64 but if you want something diferent you can declare
a=np.array([1,2,65],dtype=np.int16)
print(a.dtype)
#but also we can change the type by concerting
print(a.astype(np.float16))


#Dimensional transformation
c1=np.array([12,4,6,89,23,-2])
c2=c1.reshape(3,2)
print(c2)
#we also have ravel and flatten to join the dimensional in one
#the diference between them is ravel return a reference while flatten the copy

#Duplication
#When we do this  a=b that's mean that a is reference b and when we change 
#the specify index that's mean that a is going to change too that's why we have this
c3=c1.copy()

# Sequence
# we use arange to determine a sequece of number
d1=np.arange(10);
d2=np.arange(1,11)
d3=np.arange(1,11,2)

#Random numbers
#first we hava np.random.random(rows, columns) _ that generety number
#we also use np.random.seed(123)
#second we have np.random.randint(rows,column) or np.random.randint(lower,highter,(rows,columns)) to generety int number
#and we have np.random.uniform(0.0, 5.0, size=(4, 2)) for float numbers
#others functions to generate arrays
print('Generete three 0:',np.zeros(3),' and with two dimensional :',np.zeros((3,3)))
print('Generate three 1:',np.ones(3))
print('Generate the both',np.eye(3))
print('Generate specify values',np.full(3,5))
print('Generate :',np.linspace(0, 1, 5))



int64
int16
[ 1.  2. 65.]
[[12  4]
 [ 6 89]
 [23 -2]]
Generete three 0: [0. 0. 0.]  and with two dimensional : [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Generate three 1: [1. 1. 1.]
Generate the both [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Generate specify values [5 5 5]
Generate : [0.   0.25 0.5  0.75 1.  ]


In [13]:
##Concatenating, Splitting, and Transforming Arrays with NumPy

#we use diff to know the difference between numbers
# we use concatenate to join numbers of different dimensioal
# we also have hsplip to divide the numbers
import numpy as np
l=np.array([[1,2,3],[3,4,6],[8,9,10]])
j=np.array([[17,5,3],[3,4,6],[8,9,10]])

#np.diff(l)
#np.concatenate([j,l])
a = np.array([[1, 2, 10], [3, 4, 20], [5, 6, 30], [7, 8, 40]])
cols,cols1=np.hsplit(a,[2])
row1, row2 = np.vsplit(a, [2])
#a.T
#a[:,np.newaxis]
#grid data
x = np.array([1, 2, 3, 4])
y = np.array([5, 6, 7])

xx,yy=np.meshgrid(x,y)
yy


array([[5, 5, 5, 5],
       [6, 6, 6, 6],
       [7, 7, 7, 7]])

In [16]:
##Eercices

# Beginner Level
# Create a NumPy array
# Create a 1D NumPy array with values from 0 to 9.
import numpy as np
x=np.arange(10)
print('x:',x)
# Create a 2D array
# Create a 3×3 NumPy array filled with random integers between 1 and 100.
np.random.seed(123)
x=np.random.randint(1,100,(3,3))
print(x)
# Array shape and reshaping
# Convert a 1D array of size 9 into a 3×3 matrix.
y=np.array([1,2,3,4,5,6,7,8,9])
y1=y.reshape((3,3))
print('Reshape',y1)

# Basic array operations
# Create two 1D NumPy arrays of the same size and perform element-wise addition, subtraction, multiplication, and division.
a=np.array([1,23,-6,90,13,50,89])
b=np.array([9,78,12,41,-20,125,99])
print('Addition :',a+b)
print('subtraction:',a-b)
print('Multiplicatiom',a*b)
print('Division',a/b)


# Boolean masking
# Given an array [10, 25, 30, 45, 50, 65], filter out elements that are greater than 30.
values=np.array( [10, 25, 30, 45, 50, 65])
print(' value greater than 30',values[values>30])
print('Boolean value greater than 30',values>30)


x: [0 1 2 3 4 5 6 7 8 9]
[[67 93 99]
 [18 84 58]
 [87 98 97]]
Reshape [[1 2 3]
 [4 5 6]
 [7 8 9]]
Addition : [ 10 101   6 131  -7 175 188]
subtraction: [ -8 -55 -18  49  33 -75 -10]
Multiplicatiom [   9 1794  -72 3690 -260 6250 8811]
Division [ 0.11111111  0.29487179 -0.5         2.19512195 -0.65        0.4
  0.8989899 ]
 value greater than 30 [45 50 65]
Boolean value greater than 30 [False False False  True  True  True]


In [23]:
# Generate an identity matrix
# Create a 5×5 identity matrix.
import numpy as np
matrix=np.eye(5)
#matrix
# Generate a diagonal matrix
# Create a 4×4 diagonal matrix with values [1, 2, 3, 4] on the diagonal.
matrix_diagonal=np.diag([1,2,3,4])
#matrix_diagonal
# Stacking arrays
# Create two 1D NumPy arrays and stack them vertically and horizontally.
array1=np.array([1,2,3,4,5])
array2=np.array([16,3,-14,89,10])
stack1=np.vstack((array1,array2))
#stack1
stack2=np.hstack((array1,array2))
#stack2
# Find the mean, median, and standard deviations
# Given an array [12, 15, 22, 29, 35, 45, 50, 60, 72, 85], compute the mean, median, and standard deviation.
arr=np.array([12, 15, 22, 29, 35, 45, 50, 60, 72, 85])
print('mean:',np.mean(arr))
print('median:',np.median(arr))
print('standard:',np.std(arr))


# Find unique elements and counts
# Given an array [1, 2, 2, 3, 3, 3, 4, 4, 4, 4], find unique elements and their counts.
arr=np.array([1, 2, 2, 3, 3, 3, 4, 4, 4, 4])
unique ,counts=np.unique(arr,return_counts=True)
print('Unique_elemets',unique)
print('Counts ',counts)


mean: 42.5
median: 40.0
standard: 23.21745033374681
Unique_elemets [1 2 3 4]
Counts  [1 2 3 4]


In [ ]:
# Replace elements in an array
# Replace all even numbers in a given array [10, 15, 20, 25, 30, 35] with -1.

# Matrix multiplication
# Multiply two matrices of size 3×3 using NumPy.

# Sorting an array
# Sort a NumPy array [12, 5, 8, 19, 2, 35, 42] in ascending and descending order.

# Find the closest value in an array
# Given a NumPy array [10, 20, 30, 40, 50], find the element closest to 33.

# Broadcasting example
# Create a 3×3 NumPy matrix and add a 1D array of shape (3,) to each row using broadcasting.