In [10]:
#First I need to know that Numpy we use tho handle mastrix (1D,2D)
#Is packge python that provide methods and functions to handle array and matrix
#Is is used in data analysis
#Lets pratice

#first we need to import 
import numpy as np
# after this we can create array with one-dimetions ou two
a=np.array([1,2,3]);
print(a)
# and to create with to tho-dimenseional is that
b=np.array([[1,23,12],[45,12,13]])
#Alright we can use this :
#type(a) to see the type , 
print('Type a :',type(a))
#shape to see the number of element
print('Shape b :',b.shape)
#ndim to see how much dimesional
print('Dim b',b.ndim);
#As you see in b we have two dimensional so for see the specific value in b we use index
print('b[0,1]:',b[0,1])
#but we  can also use this to ond  dimensional
#anyway we also use this b[-1] to retrieved the last number 
# we can use this b[1,:] just to retrieved the among numbers in the the index 1 
#we also use this b[0:1] to change the number in this specif index


[1 2 3]
Type a : <class 'numpy.ndarray'>
Shape b : (2, 3)
Dim b 2
b[0,1]: 23


In [21]:
#Varios methods in Numpy
#What is diference between function and method
#In numpy we have functions as sum()
a=np.array([12,14,16]);
np.sum(a)
a.sum()
#let is talk about dtype
print(a.dtype)
#basycally all the data is define as int64 but if you want something diferent you can declare
a=np.array([1,2,65],dtype=np.int16)
print(a.dtype)
#but also we can change the type by concerting
print(a.astype(np.float16))


#Dimensional transformation
c1=np.array([12,4,6,89,23,-2])
c2=c1.reshape(3,2)
print(c2)
#we also have ravel and flatten to join the dimensional in one
#the diference between them is ravel return a reference while flatten the copy

#Duplication
#When we do this  a=b that's mean that a is reference b and when we change 
#the specify index that's mean that a is going to change too that's why we have this
c3=c1.copy()

# Sequence
# we use arange to determine a sequece of number
d1=np.arange(10);
d2=np.arange(1,11)
d3=np.arange(1,11,2)

#Random numbers
#first we hava np.random.random(rows, columns) _ that generety number
#we also use np.random.seed(123)
#second we have np.random.randint(rows,column) or np.random.randint(lower,highter,(rows,columns)) to generety int number
#and we have np.random.uniform(0.0, 5.0, size=(4, 2)) for float numbers
#others functions to generate arrays
print('Generete three 0:',np.zeros(3),' and with two dimensional :',np.zeros((3,3)))
print('Generate three 1:',np.ones(3))
print('Generate the both',np.eye(3))
print('Generate specify values',np.full(3,5))
print('Generate :',np.linspace(0, 1, 5))



int64
int16
[ 1.  2. 65.]
[[12  4]
 [ 6 89]
 [23 -2]]
Generete three 0: [0. 0. 0.]  and with two dimensional : [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Generate three 1: [1. 1. 1.]
Generate the both [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Generate specify values [5 5 5]
Generate : [0.   0.25 0.5  0.75 1.  ]


In [ ]:
##

In [1]:
##Eercices

# Beginner Level
# Create a NumPy array
# Create a 1D NumPy array with values from 0 to 9.
import numpy as np
x=np.arange(10)
print('x:',x)
# Create a 2D array
# Create a 3×3 NumPy array filled with random integers between 1 and 100.
np.random.seed(123)
x=np.random.randint(1,100,(3,3))
print(x)
# Array shape and reshaping
# Convert a 1D array of size 9 into a 3×3 matrix.
y=np.array([1,2,3,4,5,6,7,8,9])
y1=y.reshape((3,3))
print('Reshape',y1)

# Basic array operations
# Create two 1D NumPy arrays of the same size and perform element-wise addition, subtraction, multiplication, and division.

# Boolean masking
# Given an array [10, 25, 30, 45, 50, 65], filter out elements that are greater than 30.

x: [0 1 2 3 4 5 6 7 8 9]
[[67 93 99]
 [18 84 58]
 [87 98 97]]
Reshape [[1 2 3]
 [4 5 6]
 [7 8 9]]
